### ISSUE TITLE
Not quite sure how to use this

### ISSUE THREAD

**Issue by denouveau** [navanchauhan/VaporwaveGenerator#11]
So I simply ran it with the following arguments:
python3 main.py -M -i D:\Downloads\unraelvel\unravel.mp3 -o D:\Downloads\unraelvel\testoutput.mp3 and it gave the following result:
[I 210331 15:08:47 main:90] Get video information...
Traceback (most recent call last):
  File "main.py", line 167, in <module>
    name, title = download_file(query)
  File "main.py", line 107, in download_file
    raise ValueError('Could not find a video.')
ValueError: Could not find a video.
Am I not doing this right? If so, what would be a correct example of it's usage?

**Comment by navanchauhan** [comment]
The input takes the title of the song and then downloads it from YouTube. If you want I'll push a patch for local audio files by the weekend.


The correct usage using the song title is `python3 main.py -M -i Song Title`

**Comment by denouveau** [comment]
That would be great. Thanks

**Comment by denouveau** [comment]
New problem, when I run the command this happens
[I 210331 16:38:23 main:111] Query was a YouTube URL.
[I 210331 16:38:24 main:120] Downloading video...
'rm' is not recognized as an internal or external command,
operable program or batch file.
'rm' is not recognized as an internal or external command,
operable program or batch file.
The syntax of the command is incorrect.
The syntax of the command is incorrect.
[I 210331 16:38:25 VaporSong:161] Slowing down the music
'sox' is not recognized as an internal or external command,
operable program or batch file.
[I 210331 16:38:25 VaporSong:165] Doing Beat Analysis
Traceback (most recent call last):
  File "main.py", line 168, in <module>
    gen_vapor(name, title)
  File "main.py", line 152, in gen_vapor
    VaporSong.vaporize_song(filePath, title)
  File "D:\Downloads\VaporwaveGenerator-2.1\VaporwaveGenerator-2.1\src\VaporSong.py", line 166, in vaporize_song
    bm = VaporSong.fetchbeats("beats/out.wav")
  File "D:\Downloads\VaporwaveGenerator-2.1\VaporwaveGenerator-2.1\src\VaporSong.py", line 55, in fetchbeats
    beats = subprocess.check_output(["get-beats",src]).rstrip()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
I already installed sox using pip and noah was not a valid package. I also installed requirements.txt

**Comment by navanchauhan** [comment]
You're using Windows. The platform isn't supported due to the requirements. 


Someone did create a Docker version of this repository though, https://hub.docker.com/r/trevorftard/vaporwave-generator


This should work on Windows
