### ISSUE TITLE
opencv error?

### ISSUE THREAD

**Issue by DEAD1SIDE** [navanchauhan/VaporwaveGenerator#4]
Hey. 
I got this error:
`Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from src.VHSVideo import VHS_Vid
  File "/root/VaporwaveGenerator/src/VHSVideo.py", line 2, in <module>
    import cv2
  File "/usr/local/lib/python3.6/dist-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory`
All needed packets are installt.
Using Ubuntu 18.04.4
opencv is installed

**Comment by DEAD1SIDE** [comment]
Got it fixed with: 
`apt install -y libsm6 libxext6`
